blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('',views.post_list, name='post_list'), # url for post_list view
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'), # url for post_detail view
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.HomeView.as_view(), name="home"),
    path("about", views.AboutView.as_view(), name="about"),
    path("contact", views.ContactView.as_view(), name="contact"),
    path("services", views.ServiceView.as_view(), name="services"),
    path("blog/", include("blog.urls"))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# from taggit.managers import TaggableManager
# Create your models here.
import sys
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES= (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    # tags = TaggableManager()

    objects = models.Manager()  # default manager
    published = PublishedManager()  # our custom manager

    class Meta:
        ordering = ('-publish',)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    def save(self, *args, **kwargs):
        imageTemporary = Image.open(self.image)
        outputIOStream = BytesIO()		
        imageTemproaryResized = imageTemporary.resize((717,515)) 
        imageTemproaryResized.save(outputIOStream , format='JPEG', quality=85)
        outputIOStream.seek(0)
        self.image = InMemoryUploadedFile(outputIOStream,'ImageField', "%s.jpg" %self.image.name.split('.')[0], 'image/jpeg', sys.getsizeof(outputIOStream), None)
        super(Post, self).save(*args, **kwargs)



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=300)
    email   =models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)
    

blog/forms.py
from django import forms
from .models import Comment




class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger  
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.db.models import Count
from .forms import CommentForm
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

# Create your views here.


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 2)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',{
        'page':page,
        'posts':posts,
    })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, 
                            slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    # List of active comments
    comments = post.comments.filter(active=True) # using the related_name in the many-to-one relationship filter acording to the active comment
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Create comment object but don't save to the database
            new_comment = comment_form.save(commit=False)
            #Assign the current post to the comment
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    # post_tags_ids = post.tags.values_list('id', flat=True)
    # similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {
        'post':post,
        'new_comment':new_comment,
        'comment_form':comment_form,
        'comments':comments,
        # 'similar_posts':similar_posts
    })

    

mysite/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.



class HomeView(TemplateView):
    template_name = "main/index.html"


class AboutView(TemplateView):
    template_name = "main/about.html"

class ContactView(TemplateView):
    template_name = "main/contact.html"


class ServiceView(TemplateView):
    template_name = "main/services.html"

blog/templates/blog/post/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Blog {% endblock %}
{% block content %}
{% include "../../main/include/navbar.html" %}

<main class="page-content">
    <section style="background-image: url(/static/images/blog-icon-information-internet-262508.jpg);" class="section-30 section-sm-40 section-md-66 section-lg-bottom-90 bg-gray-dark page-title-wrap">
      <div class="shell">
        <div class="page-title">
          <h2>Blog</h2>
        </div>
      </div>
    </section>
    <section class="section-50 section-sm-75 section-lg-100">
      <div class="shell">
        <div class="range range-sm-center">
          <div class="cell-lg-10">
            <dl class="blog-timeline">
              <dt> {% now "Y" %}</dt>
              <dd>

                {% for post in posts %}
                <article class="post-classic-minimal">
                  <div class="post-left">
                    <time datetime="{{post.publish}}">{{post.publish|date:"M d"}}</time>
                  </div>
                  <div class="post-main">
                    <div class="post-media post-gallery">
                      <figure><a href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="" width="771" height="515"/>
                      </a>
                           </figure>
                    </div>
                    <div class="post-header">
                      <h4><a href="{{ post.get_absolute_url }}">{{  post.title }}</a></h4>
                      <p>
                        {{ post.body|truncatewords:15 }}
                    </p>
                    </div>
                    <div class="post-footer">
                      <ul class="post-meta">
                        <li>
                          <dl>
                            <dt>by</dt>
                            <dd>
                              {% if post.author.first_name %}  
                              {{post.author.first_name}} {{post.author.last_name}}
                          {% else %}
                              {{post.author}}
                          {% endif %}
                            </dd>
                          </dl>
                        </li>
                      </ul>
                    </div>
                  </div>
                </article>
                {% endfor %}

                

                <div class="offset-top-40 offset-sm-top-60 offset-lg-top-90 inset-lg-left-100 text-center">
                  <ul class="pagination-custom">
                    <li>
                      <!-- <a href="#">Previous</a> -->

                      {% if page.has_previous %}
                      <a href="#">Previous</a>
                      <!-- <a href="?page={{ page.previous_page_number }}">Previous</a> -->
                      {% else%}
                      <!-- NOne -->
                      {% endif %}                    
                    </li>
                    <!-- <span class="current">
                      Page {{ page.number }} of {{ page.paginator.num_pages }}.
                      </span> -->
                    <li>
                      {% if page.has_next %}
                      <a href="?page={{ page.next_page_number }}">Next</a>
                      {% else%}
                      <!-- None -->
                      {% endif %}
                    
                    </li>
                  </ul>
                </div>
              </dd>
            </dl>
          </div>
        </div>
      </div>
    </section>
  </main>
{% endblock %}

<!-- <div class="pagination">
  <span class="step-links">
  {% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}">Previous</a>
  {% endif %}
  <span class="current">
  Page {{ page.number }} of {{ page.paginator.num_pages }}.
  </span>
  {% if page.has_next %}
  <a href="?page={{ page.next_page_number }}">Next</a>
  {% endif %}
  </span>
  </div> -->

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
      {% block title %}
      Enenu
      {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/css.css?family=Roboto:100,300,400,500,700%7CPlayfair+Display:400,700,700i,900,900i' %}">
    <link rel="stylesheet" href="{%static 'css/style.css' %}">

</head>
<body>
    <div class="page">

    {% block content %}
    {% endblock %}
    <script src="{% static 'js/core.min.js' %}"></script> 
    <script src="{% static 'js/script.js' %}"></script>
    <footer class="page-foot bg-cape-cod context-dark">
        <section class="section-40 section-sm-75">
          <div class="shell">
            <div class="range range-xs-center">
              <div class="cell-xs-9 cell-sm-11 cell-lg-12">
                <div class="range">
                  <div class="cell-sm-6 cell-md-10 cell-lg-3">
                    <div style="max-width: 510px;" class="inset-lg-right-20">
                      <a href="{% url 'home'%}" class="brand brand-inverse"><img src="{% static 'images/enenulogo2.jpg' %}" alt="logo" width="135" height="34"/></a>
                      <p class="offset-top-22 text-dusty-gray">
                        We sell shoes, bags,  jeans, dresses, blazers,  
                        suits, fabrics, all fashion accessories,   
                        perfumes, hair, sports clothing and many more.
                    </p>
                      <a href="{% url 'contact'%}" class="text-small-16 text-medium offset-top-15">Free Consultation</a> </div>
                  </div>
                  <div class="cell-sm-6 cell-md-4 cell-lg-3 offset-top-50 offset-lg-top-0">
                    <h6 class="text-small-16 text-uppercase">Quick links</h6>
                    <div style="max-width: 270px;" class="row offset-top-22 offset-md-top-30">
                      <div class="col-xs-6">
                        <ul class="list-marked-variant-2">
                          <li><a href="{% url 'home'%}">Home</a></li>
                          <li><a href="{% url 'services'%}">Services</a></li>
                          
                          <li><a href="#">Blog</a></li>
                        </ul>
                      </div>
                      <div class="col-xs-6">
                        <ul class="list-marked-variant-2">
                          <li><a href="{% url 'about'%}">About us</a></li>
                          <li><a href="{% url 'contact'%}">Contacts</a></li>
                          
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="cell-sm-6 cell-md-4 cell-lg-3 offset-top-50 offset-lg-top-0">
                    <h6 class="text-small-16 text-uppercase">Contact us</h6>
                    <address class="contact-info offset-top-22 offset-md-top-30 offset-lg-top-35 text-left">
                    <div class="unit unit-horizontal unit-spacing-md unit-middle">
                      <div class="unit-left"><span class="icon icon-xs icon-dusty-gray material-icons-phone"></span></div>
                      <div class="unit-body"><a href="callto:#" class="link-white">+2348101118476</a></div>
                    </div>
                    <div class="unit unit-horizontal unit-spacing-md unit-middle offset-top-15">
                      <div class="unit-left"><span class="icon icon-xs icon-dusty-gray fa fa-envelope-o"></span></div>
                      <div class="unit-body"><a href="#5d7e" class="link-white">
                        <span class="__cf_email__" data-cfemail="442d2a222b042021292b282d2a2f6a2b3623">
                          enenuwears@gmail.com</span></a></div>
                    </div>
                    <div class="unit unit-horizontal unit-spacing-md offset-top-15">
                      <div class="unit-left"><span class="icon icon-xs icon-dusty-gray material-icons-place"></span></div>
                      <div class="unit-body"><a href="#" class="link-white reveal-inline">6036 Richmond hwy,<br>
                        Alexandria, VA USA 22303</a></div>
                    </div>
                    </address>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div class="shell">
          <hr class="hr bg-abbey-04">
        </div>
        <section class="section-35">
          <div class="shell text-center">
            <div class="range range-sm-reverse range-sm-justify range-sm-middle">
              <div class="cell-sm-6 text-sm-right">
                <div class="group-sm group-middle">
                  <p class="text-italic text-white">Follow Us:</p>
                  <ul class="list-inline list-inline-reset">
                    <li><a href="#" class="icon icon-round icon-abbey-filled icon-xxs-smallest fa fa-facebook"></a></li>
                    <li><a href="#" class="icon icon-round icon-abbey-filled icon-xxs-smallest fa fa-twitter"></a></li>
                    <li><a href="#" class="icon icon-round icon-abbey-filled icon-xxs-smallest fa fa-google-plus"></a></li>
                  </ul>
                </div>
              </div>
              <div class="cell-sm-6 offset-top-15 offset-sm-top-0 text-sm-left">
                <p class="rights text-white"><span id="copyright-year"></span><span>&nbsp;&#169;&nbsp;</span><span>Enenu.&nbsp;</span>
                  <a href="#" class="link-white-v2">Privacy Policy</a> </p>
              </div>
            </div>
          </div>
        </section>
      </footer>
</div>

</body>
</html>

templates/main/contact.html
{% extends 'base.html' %}
{% block title %}
Contact
{% endblock %}
{% block content %}
{% include "./include/navbar.html" %}

<main class="page-content">
    <!-- /home/goodness/Documents/Enenu/src/static/images/cellphone-cellular-communication-connection-263564.jpg -->
    <section style="background-image: url(/static/images/cellphone-cellular-communication-connection-263564.jpg);" class="section-30 section-sm-40 section-md-66 section-lg-bottom-90 bg-gray-dark page-title-wrap">
      <div class="shell">
        <div class="page-title">
          <h2>Contact Us</h2>
        </div>
      </div>
    </section>
    <section class="section-60 section-sm-top-90 section-sm-bottom-100">
      <div class="shell">
        <div class="range range-xs-center range-md-left">
          <div class="cell-md-7 cell-lg-6">
            <h3>Get in <span class="text-thin">Touch</span></h3>
            <form data-form-output="form-output-global" data-form-type="contact" method="post" action="#" class="rd-mailform form-modern offset-top-15">
              <div class="range">
                <div class="cell-sm-6">
                  <div class="form-group">
                    <input id="contact-name" type="text" name="name" data-constraints="@Required" class="form-control">
                    <label for="contact-name" class="form-label">Name</label>
                  </div>
                </div>
                <div class="cell-sm-6 offset-top-30 offset-sm-top-0">
                  <div class="form-group">
                    <input id="contact-email" type="email" name="email" data-constraints="@Email @Required" class="form-control">
                    <label for="contact-email" class="form-label">Email</label>
                  </div>
                </div>
                <div class="cell-xs-12 offset-top-30">
                  <div class="form-group">
                    <div class="textarea-lined-wrap">
                      <textarea id="contact-message" name="message" data-constraints="@Required" class="form-control"></textarea>
                      <label for="contact-message" class="form-label">Message</label>
                    </div>
                  </div>
                </div>
                <div class="cell-xs-8 offset-top-30 offset-xs-top-30 offset-sm-top-60">
                  <button type="submit" class="btn btn-primary btn-block">Send</button>
                </div>
                <div class="cell-xs-4 offset-top-22 offset-xs-top-30 offset-sm-top-60">
                  <button type="reset" class="btn btn-silver-outline btn-block">Reset</button>
                </div>
              </div>
            </form>
          </div>
          <div class="cell-lg-1 veil reveal-lg-inline-block"></div>
          <div class="cell-md-5 cell-lg-4 offset-top-50 offset-md-top-0">
            <div class="range">
              <div class="cell-sm-10 cell-md-12">
                <h3>How to <span class="text-thin">Find Us</span></h3>
                <p class="offset-sm-top-30 text-secondary"> If you have any questions, just fill in the contact form, and we will answer you shortly. If you are living nearby, come visit us. </p>
              </div>
              <div class="cell-sm-6 cell-md-12 offset-top-35">
                <h4>Headquarters</h4>
                <address class="contact-info">
                <p class="text-uppercase">9863 - 9867 MILL ROAD, CAMBRIDGE, MG09 99HT.</p>
                <dl class="list-terms-inline">
                  <dt>Telephone</dt>
                  <dd><a href="callto:#" class="link-secondary">+2348101118476</a></dd>
                </dl>
                <dl class="list-terms-inline">
                  <dt>E-mail</dt>
                  <dd><a href="#280b" class="link-primary">
                      <span class="__cf_email__" data-cfemail="4c212d25200c282921232025222762233e2b">
                        enenuwears@gmail.com</span></a></dd>
                </dl>
                </address>
              </div>
              <div class="cell-sm-6 cell-md-12 offset-top-35">
                <h4>Support Centre</h4>
                <address class="contact-info">
                <p class="text-uppercase">9870 ST VINCENT PLACE, GLASGOW, DC 45 FR 45</p>
                <dl class="list-terms-inline">
                  <dt>Telephone</dt>
                  <dd><a href="callto:#" class="link-secondary">+2348101118476</a></dd>
                </dl>
                <dl class="list-terms-inline">
                  <dt>E-mail</dt>
                  <dd><a href="#c5e6" class="link-primary">
                      <span class="__cf_email__" data-cfemail="523f333b3e1236373f3d3e3b3c397c3d2035">
                        enenuwears@gmail.com</span></a></dd>
                </dl>
                </address>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="rd-google-map">
      <div class="overlay rd-google-map__model" onClick="style.pointerEvents='none'"></div>
      <iframe  class="rd-google-map__model" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387142.8404068987!2d-74.2581973675357!3d40.70583158554698!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2zVGjDoG5oIHBo4buRIE5ldyBZb3JrLCBUaeG7g3UgYmFuZyBOZXcgWW9yaw!5e0!3m2!1svi!2s!4v1480613299202" allowfullscreen></iframe>
    </div>
  </main>
{% endblock %}

templates/main/include/navbar.html
{% load static %}
  <header class="page-head">
    <div class="rd-navbar-wrap">
      <nav data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-stick-up-clone="false" data-md-stick-up-offset="53px" data-lg-stick-up-offset="53px" data-md-stick-up="true" data-lg-stick-up="true" class="rd-navbar rd-navbar-corporate-dark">
        <div class="rd-navbar-inner">
          <div class="rd-navbar-aside">
            <div data-custom-toggle=".rd-navbar-aside" data-custom-toggle-disable-on-blur="true" class="rd-navbar-aside-toggle"><span></span></div>
            <div class="rd-navbar-aside-content context-dark">
              <ul class="rd-navbar-aside-group list-units">
                <li>
                  <div class="unit unit-horizontal unit-spacing-xs">
                    <div class="unit-left"><span class="icon icon-xxs-small icon-primary material-icons-place icon-shift-1 offset-top-2"></span></div>
                    <div class="unit-body"><a href="#" class="link-white-v2 reveal-inline">2381 Rosecrans Ave,  CA 90245. USA</a></div>
                  </div>
                </li>
                <li>
                  <div class="unit unit-horizontal unit-spacing-xs">
                    <div class="unit-left"><span class="icon icon-xxs icon-primary fa-clock-o offset-top-2"></span></div>
                    <div class="unit-body">
                      <p class="text-white">Mon – Sat: 9:00am–18:00pm. Sunday CLOSED</p>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="unit unit-horizontal unit-spacing-xs">
                    <div class="unit-left"><span class="icon icon-xxs icon-primary material-icons-phone icon-shift-2"></span></div>
                    <div class="unit-body"><a href="callto:#" class="link-white-v2">+2348101118476</a></div>
                  </div>
                </li>
              </ul>
              <div class="rd-navbar-aside-group">
                <ul class="list-inline list-inline-reset">
                  <li><a href="#" class="icon icon-round icon-abbey-filled icon-xxs-smallest fa fa-facebook"></a></li>
                  <li><a href="#" class="icon icon-round icon-abbey-filled icon-xxs-smallest fa fa-twitter"></a></li>
                  <li><a href="#" class="icon icon-round icon-abbey-filled icon-xxs-smallest fa fa-google-plus"></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="rd-navbar-group rd-navbar-search-wrap">
            <div class="rd-navbar-panel">
              <button data-custom-toggle=".rd-navbar-nav-wrap" data-custom-toggle-disable-on-blur="true" class="rd-navbar-toggle"><span></span></button>
              <a href="{% url 'home'%}" class="rd-navbar-brand brand"><img src="{% static 'images/logo.jpeg' %}" alt="logo" width=100 height="34"/></a> </div>
            <div class="rd-navbar-nav-wrap">
              <div class="rd-navbar-nav-inner">
                <div class="rd-navbar-search">
                  <form action="search-results.html" method="GET" data-search-live="rd-search-results-live" class="rd-search">
                    <div class="form-group">
                      <label for="rd-search-form-input" class="form-label">Search...</label>
                      <input id="rd-search-form-input" type="text" name="s" autocomplete="off" class="form-control">
                      <div id="rd-search-results-live" class="rd-search-results-live"></div>
                    </div>
                    <button type="submit" class="rd-search-submit"></button>
                  </form>
                  <!-- <button data-rd-navbar-toggle=".rd-navbar-search, .rd-navbar-search-wrap" class="rd-navbar-search-toggle"></button> -->
                </div>
                <ul class="rd-navbar-nav">
                  <li class="active"><a href="{% url 'home' %}">Home</a> </li>
                  <li><a href="{% url 'about'%}">About Us</a> </li>
                  <li><a href="{% url 'services'%}">Services</a> </li>
                  <li><a href="{% url 'blog:post_list'%}">Blog</a>
                  </li>
                  <li><a href="{% url 'contact' %}">Contacts</a> </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </header>